---
title: "Young people - digital world"
author: "Joseph"
editor: visual
toc: true
toc-location: left
code-link: true
code-line-numbers: true
linkcolor: blue
output-file: "Digital World"
---

## Article Source

The figures here are replicated from [Young people - digital world](https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Young_people_-_digital_world).

## Loading Packages

```{r}
#| warning: false
#| message: false


require(conflicted)

require(restatapi)
require(giscoR)

require(data.table)
require(chron)
require(reshape2)

require(kableExtra)
require(tidyverse)
require(tmap)

require(highcharter)
require(plotly)
```

## Figure 7

### Retrieving data

```{r}
id7<-"isoc_sk_dskl_i21"
date7 = 2020

eu_cc<-get("cc",envir=.restatapi_env)$EU27_2020

efta_cc<-c("CH","NO","IS","LI")

data7 = get_eurostat_data(
  id2, 
  filters = list(
    incgrp = c("TOTAL","B_MD60"),
    freq = "Annual",
    hhtyp = "TOTAL",
    unit = "Percentage"
  ),date_filter = eval(date2),
  label=T,
  ignore.case=T,
  exact_match=F,
  perl=T,
  stringsAsFactors=F,
  force_local_filter=T)

dsd<-as.data.table(get_eurostat_dsd(id2))[concept=="geo",c("code","name")]

datafig2<-merge(data7, dsd, 
             by.x="geo",by.y="name", 
             all.x=T, all.y = F)

datafig7 <- datafig7[!code %in% c("EA19", "EA18", "EA", "EU28", "EU27_2007", "EU")]

datafig7$geo<-gsub(" \\(.*\\)","",datafig7$geo)




datafig7$geo<-gsub("^Eu.*","EU",datafig7$geo)


name_ord <- datafig7[(code %in% eu_cc) & (incgrp == "Total")]

name_ord_eu<-name_ord[order(values)]$geo

name_ord<-datafig7[(code %in% efta_cc) & (incgrp == "Total")]

name_ord_efta<-name_ord[order(values)]$geo

name_ord<-datafig7[!(code %in% c(efta_cc,eu_cc,"EU27_2020")) & (incgrp == "Total")]

name_ord_othr<-name_ord[order(values)]$geo

name_ord<-c(name_ord_othr, " " ,name_ord_efta, "  " ,name_ord_eu, "   ", "EU")

datafig7 <- datafig7 |>
  select(geo, incgrp, values) |>
  mutate(incgrp = recode(incgrp,
                         "Below 60% of median equivalised income" = "Population at-risk-of-poverty (\U00B2)")) |>
  (\(df){
    dt_sep <- data.table::data.table(
      geo = c(" ", "  ", "   "),
      incgrp = rep("Total", 3),
      values = rep(NA, 3)
    )
    rbind(df, dt_sep)
  })()

datafig7$geo <- factor(datafig7$geo,levels = rev(name_ord))
datafig7$incgrp <- factor(datafig7$incgrp, levels = c("Total", "Population at-risk-of-poverty (\U00B2)"))

datafig7 <- datafig7 |>
  mutate(geo = recode(geo,
                      "France" = "France (\U00B3)",
                      "Luxembourg" = "Luxembourg (\U00B3)",
                      "Germany" = "Germany (\U00B3)(\U2075)",
                      "Ireland" = "Ireland (\U00B3)",
                      "EU" = "EU (\U00B9)"))


```


